import type { LPStatus, StackItem, DataDocStatus } from "./types";

export const lpStatus: LPStatus[] = [
  {
    slug: "multi-pots",
    title: "Multi-pots — « Tu as 5 pots, tu en as besoin d'un »",
    angle: "a-multi-pots",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "tiktok", "email"],
    url: "/lp/multi-pots",
    liveSince: "2026-04-13",
    nextActions: ["Brancher pixel Meta + UTM", "Créer 3 creatives UGC pour test"],
  },
  {
    slug: "digestion",
    title: "Digestion — « Le ventre qui te laisse tranquille »",
    angle: "a-digestion",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "tiktok"],
    url: "/lp/digestion",
    liveSince: "2026-04-13",
  },
  {
    slug: "stress-sommeil",
    title: "Stress & Sommeil — Ashwagandha KSM-66",
    angle: "a-stress-sommeil",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "tiktok", "snapchat"],
    url: "/lp/stress-sommeil",
    liveSince: "2026-04-13",
  },
  {
    slug: "halal",
    title: "Halal — Pectine natif, pas adapté",
    angle: "a-halal",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "snapchat", "tiktok"],
    url: "/lp/halal",
    liveSince: "2026-04-13",
    nextActions: ["Influenceurs halal FR à contacter", "Partenariats Al-Kanz / mosquées"],
  },
  {
    slug: "pilules",
    title: "Pilules — Quitte tes comprimés",
    angle: "a-pilules",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "email"],
    url: "/lp/pilules",
    liveSince: "2026-04-13",
  },
  {
    slug: "energie",
    title: "Énergie — Crash de 15h",
    angle: "a-energie",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "tiktok"],
    url: "/lp/energie",
    liveSince: "2026-04-13",
  },
  {
    slug: "made-in-france",
    title: "Made in France — Le Grüns français",
    angle: "—",
    status: "paused",
    owner: "Sabri",
    trafficSources: [],
    url: "/lp/made-in-france",
    liveSince: "2026-04-13",
    blocker: "Angle invalidé — produit sourcé en Chine. Reformuler le copy (retirer MIF, pivoter sur dosages / halal / prix) ou retirer la LP de prod.",
  },
  {
    slug: "immunite",
    title: "Immunité — 4 piliers hiver",
    angle: "a-immunite",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "email"],
    url: "/lp/immunite",
    liveSince: "2026-04-13",
    nextActions: ["Saisonnier — réactiver sept-mars"],
  },
  {
    slug: "arnaque",
    title: "Arnaque — On te laisse vérifier",
    angle: "a-arnaque",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "email", "organic"],
    url: "/lp/arnaque",
    liveSince: "2026-04-13",
  },
  {
    slug: "parents",
    title: "Parents — Ta nutrition passe en dernier",
    angle: "a-parents",
    status: "live",
    owner: "Sabri",
    trafficSources: ["meta", "tiktok", "snapchat"],
    url: "/lp/parents",
    liveSince: "2026-04-13",
  },
];

export const stackItems: StackItem[] = [
  { category: "frontend", name: "Next.js 16 + React 19", usage: "Site + LPs + Atlas HQ", status: "live" },
  { category: "frontend", name: "Tailwind 4 + Framer Motion", usage: "UI / animations", status: "live" },
  { category: "hosting", name: "Hostinger (FTP)", usage: "gomudaily.com + LPs statiques", status: "live", notes: "Build → /out/ → FTP via GitHub Actions" },
  { category: "analytics", name: "GA4 + Meta Pixel", usage: "Tracking funnel + UTM", status: "planned", notes: "À câbler avant le premier budget pub" },
  { category: "ads", name: "Meta Ads Manager", usage: "Acquisition principale FR", status: "planned" },
  { category: "ads", name: "TikTok Ads Manager", usage: "Acquisition Gen Z + parents", status: "planned" },
  { category: "ads", name: "Snapchat Ads", usage: "Segment halal + Gen Z", status: "planned" },
  { category: "email", name: "Klaviyo (à évaluer) ou Brevo", usage: "Welcome + cart + post-purchase", status: "evaluating", notes: "Brevo = moins cher FR, Klaviyo = meilleur intégration DTC" },
  { category: "payment", name: "Stripe + Shopify Subscriptions", usage: "Checkout + abonnements", status: "planned" },
  { category: "fulfillment", name: "Façonnier FR (Irati International ciblé)", usage: "Fabrication + conditionnement", status: "evaluating" },
  { category: "fulfillment", name: "3PL FR (à définir)", usage: "Stock + expéditions", status: "planned" },
  { category: "support", name: "Crisp ou Intercom", usage: "Chat + email client", status: "planned" },
];

export const dataDocStatus: DataDocStatus[] = [
  { path: "data/BIBLE_FONDAMENTALE.md", title: "Bible fondamentale", sizeKb: 81, consumedByLPs: ["multi-pots", "halal", "arnaque"], consumedPct: 40 },
  { path: "data/CONTEXTE_MARQUE_BRANDING.md", title: "Brand & branding", sizeKb: 8, consumedByLPs: ["all"], consumedPct: 100 },
  { path: "data/CONTEXTE_PRODUIT.md", title: "Produit & formule", sizeKb: 8, consumedByLPs: ["all"], consumedPct: 100 },
  { path: "data/AVATAR_360.md", title: "Avatars 360°", sizeKb: 58, consumedByLPs: ["parents", "halal", "energie"], consumedPct: 70 },
  { path: "data/15_ANGLES_PUB.md", title: "15 angles publicitaires", sizeKb: 42, consumedByLPs: ["all"], consumedPct: 66, },
  { path: "data/MASS_DESIRES.md", title: "10 désirs de masse", sizeKb: 51, consumedByLPs: ["multi-pots", "energie"], consumedPct: 30 },
  { path: "data/6_SOUFFRANCE.md", title: "Matrice souffrance 6×5", sizeKb: 45, consumedByLPs: ["placard"], consumedPct: 50 },
  { path: "data/NECESSARY_BELIEFS.md", title: "One Belief + croyances", sizeKb: 35, consumedByLPs: ["all"], consumedPct: 80 },
  { path: "data/MECANISMES_UNIQUES.md", title: "UMP + UMS", sizeKb: 42, consumedByLPs: ["multi-pots", "arnaque"], consumedPct: 60 },
  { path: "data/STRATEGIE_DIRECTRESPONSE.md", title: "Stratégie DR", sizeKb: 57, consumedByLPs: [], consumedPct: 40 },
  { path: "data/OFFRE.md", title: "Offre Hormozi", sizeKb: 37, consumedByLPs: ["all"], consumedPct: 90 },
  { path: "data/GARANTIE.md", title: "Garantie Sachet Vide", sizeKb: 23, consumedByLPs: ["all"], consumedPct: 100 },
  { path: "data/VOIX_DU_CLIENT.md", title: "Voix du client (synthèse)", sizeKb: 54, consumedByLPs: ["all"], consumedPct: 50 },
  { path: "data/VERBATIM1_REDDIT.md", title: "Verbatims V1 (Trustpilot FR, presse)", sizeKb: 32, consumedByLPs: ["arnaque"], consumedPct: 30 },
  { path: "data/VERBATIM2_AMAZON.md", title: "Verbatims V2 (Amazon.fr)", sizeKb: 18, consumedByLPs: ["energie"], consumedPct: 25 },
  { path: "data/VERBATIM3_LIBRE.md", title: "Verbatims V3 (blogs, forums, Quora)", sizeKb: 46, consumedByLPs: [], consumedPct: 20 },
];
